// Interactive first-time setup: prompts for a speech-to-text provider and
// its credentials (plus an optional relay auth token), and writes them to
// server/.env, which dotenv/config loads automatically on server startup.
// .env is gitignored, so keys never leave this machine or get committed.
//
// Run with: npm run setup

import { createInterface } from "node:readline/promises";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(__dirname, "..", ".env");

function parseEnvFile(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

async function main() {
  const existing = existsSync(envPath) ? parseEnvFile(readFileSync(envPath, "utf8")) : {};

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = async (question, defaultValue) => {
    const suffix = defaultValue ? ` [${defaultValue}]` : "";
    const answer = (await rl.question(`${question}${suffix}: `)).trim();
    return answer || defaultValue || "";
  };

  console.log("Copilot Terminal relay — one-time setup\n");
  console.log("Pick a speech-to-text provider for voice replies. Any one is enough:");
  console.log("  1) Azure Speech    — https://portal.azure.com (Speech resource -> Keys and Endpoint)");
  console.log("  2) OpenAI Whisper  — https://platform.openai.com/api-keys");
  console.log("  3) Google Gemini   — https://aistudio.google.com/apikey (has a free tier)\n");

  const defaultChoice = existing.AZURE_SPEECH_KEY ? "1" : existing.OPENAI_API_KEY ? "2" : existing.GEMINI_API_KEY ? "3" : "3";
  const choice = await ask("Provider (1/2/3)", defaultChoice);

  const lines = ["# Generated by `npm run setup`. Not committed to git (see .gitignore)."];

  if (choice === "1") {
    const key = await ask("Azure Speech key (AZURE_SPEECH_KEY)", existing.AZURE_SPEECH_KEY);
    const region = await ask("Azure Speech region, e.g. eastus (AZURE_SPEECH_REGION)", existing.AZURE_SPEECH_REGION);
    lines.push(`STT_PROVIDER=azure`, `AZURE_SPEECH_KEY=${key}`, `AZURE_SPEECH_REGION=${region}`);
  } else if (choice === "2") {
    const key = await ask("OpenAI API key (OPENAI_API_KEY)", existing.OPENAI_API_KEY);
    lines.push(`STT_PROVIDER=openai`, `OPENAI_API_KEY=${key}`);
  } else {
    const key = await ask("Gemini API key (GEMINI_API_KEY)", existing.GEMINI_API_KEY);
    lines.push(`STT_PROVIDER=gemini`, `GEMINI_API_KEY=${key}`);
  }

  const token = await ask(
    "Optional relay auth token (RELAY_TOKEN) — leave blank to skip (fine on a trusted home LAN)",
    existing.RELAY_TOKEN
  );
  if (token) lines.push(`RELAY_TOKEN=${token}`);

  rl.close();

  writeFileSync(envPath, lines.join("\n") + "\n", "utf8");
  console.log(`\nSaved to ${envPath}`);
  console.log("Start the relay with: npm start");
}

main().catch((err) => {
  console.error("Setup failed:", err.message);
  process.exit(1);
});
